#!/usr/bin/env php
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Xiami\Console\Command\LoginCommand;
use Xiami\Console\Command\LogoutCommand;
use Xiami\Console\Command\SongCommand;
use Xiami\Console\Command\AlbumCommand;
use Xiami\Console\Command\CollectionCommand;
use Xiami\Console\Command\MySongsCommand;
use Xiami\Console\Command\DailyRecommendationCommand;

$application = new Application('
 _|      _|   _|_|_|     _|_|     _|      _|   _|_|_|                  _|_|_|   _|         _|_|_|  
   _|  _|       _|     _|    _|   _|_|  _|_|     _|                  _|         _|           _|    
     _|         _|     _|_|_|_|   _|  _|  _|     _|     _|_|_|_|_|   _|         _|           _|    
   _|  _|       _|     _|    _|   _|      _|     _|                  _|         _|           _|    
 _|      _|   _|_|_|   _|    _|   _|      _|   _|_|_|                  _|_|_|   _|_|_|_|   _|_|_|  

<info>xiami-cli</info> version', '<comment>1.0</comment>');

$application->add(new LoginCommand());
$application->add(new LogoutCommand());
$application->add(new SongCommand());
$application->add(new AlbumCommand());
$application->add(new CollectionCommand());
$application->add(new MySongsCommand());
$application->add(new DailyRecommendationCommand());
$application->run();
